[WIP] Test insights with custom rules
konveyor-ecosystem/kantra-cli-tests pull request #26
Opened 2024-08-27 04:36 UTC by nachandr

2024-08-28 23:27 UTC, nachandr commented
![Aug28_custom_rules_Insights](https://github.com/user-attachments/assets/042c2bf3-08e6-46db-acc0-416ce6fefc7b)

2024-08-30 07:32 UTC, abrugaro requested changes
The test itself LGTM but we're rapidly increasing the size of the repository 

I created a method called `extract_zip_to_temp_dir` under `kantra-cli-tests/utils/common.py`.


By using that method, you should be able to upload the tackle testapp to the repository as a zip file instead of a folder, that way we reduce the size of the project.

Could you please try to use that for this test? You have an example of how to use it in 
`kantra-cli-tests/tests/analysis/dotnet/test_dotnet_analysis.py`

2024-08-30 07:34 UTC, abrugaro approved these changes
LGTM

2024-09-03 18:29 UTC, sshveta approved these changes

2024-09-03 18:30 UTC, merged